version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: rootpassword
      # MONGO_INITDB_DATABASE: db
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: