schema: [./src/gql/schema.ts]

generates:
  src/types/gen-types.d.ts:
    config:
      useIndexSignature: true
      defaultMapper: any
      contextType: ./context#Context
    plugins:
      - typescript
      - typescript-resolvers

hooks:
  afterAllFileWrite:
    - prettier --write
  afterOneFileWrite:
    - prettier --write
